export default function AdPolicy() {
  return (
    <div className="p-4 text-slate-900">
      <p className="text-md font-semibold italic my-2">
        Effective date: 25/01/2024
      </p>

      <p className="text-md my-2">
        Welcome to OpenEnded ("We", "Us", "Our"), the digital platform designed
        to bring thoughts and ideas together from all over the world. At
        OpenEnded, we are dedicated to protecting your privacy and ensuring a
        secure, user-friendly experience. This Ad Policy outlines how we manage
        advertising on our platform.
      </p>

      <p className="text-md my-2">
        We are committed to respecting your ("You", "User") privacy and
        prioritize the security of your personal information. This Ad Policy
        focuses on the procedures related to advertising commission, revenue
        distribution, and user eligibility for payouts.
      </p>

      <p className="text-2xl my-4">1. Advertising Commission</p>

      <p className="text-md my-2">
        Advertising commission is calculated based on the total number of views
        per user across all posted content. OpenEnded takes a 40% commission
        from the total advertising revenue generated by your content.
      </p>

      <p className="text-md my-2">
        Payouts are not backdated, and users must have a valid debit card or
        credit card linked to their account for eligibility.
      </p>

      <p className="text-2xl my-4">2. Your Choices and Rights</p>

      <p className="text-md my-2">
        You can review, modify or delete your bank information at any time that
        is in compliance with General Data Protection Regulation (GDPR).
      </p>

      <p className="text-2xl my-4">3. Contact Us</p>

      <p className="text-md my-2">
        If you have questions or concerns about our Privacy Policy, please
        contact us at team@openended.com. We are committed to addressing your
        inquiries promptly and transparently.
      </p>

      <p className="text-2xl my-4">4. Updates to Our Ad Policy</p>

      <p className="text-md my-2">
        We may update this Ad Policy to reflect changes in our advertising
        practices. When we do so, the revised date at the top of this policy
        will be updated. We encourage you to check the policy periodically for
        updates.
      </p>

      <p className="text-2xl my-4">5. Conclusion</p>

      <p className="text-md my-2">
        By using OpenEnded, you agree to this Ad Policy. Your continued use of
        the app signifies your consent to our advertising practices. Thank you
        for choosing OpenEnded – where Ideas come together.
      </p>
    </div>
  );
}
