const STRIPE_SECRET_KEY =
  "sk_test_51MPpHXARPqfde7N5Uo2L5r9E3MZwR7qNHPKbCFvIrqJa3pnzcm3tV6TRRksCP4ZEC7bugRFOkzjnJ4oXgESlARaN00nakZTXkG";
const STRIPE_PUBLISHABLE_KEY =
  "pk_test_51MPpHXARPqfde7N5ZVZicL8SRNwvzvoyFe7vCgCID73swbWAn0JtbjuscgsC0mQmbZrdW7w340LOLAVV0TadxV6e00LNsJGPyl";
const STRIPE_WEBHOOK_KEY = "whsec_9AeG0LIX9YcqMhh9UJjp73LdMViOgUXm";
const STRIPE_PRICE_ID = "price_1QsPXcARPqfde7N54pB1MlEL";

module.exports = {
  STRIPE_SECRET_KEY,
  STRIPE_PUBLISHABLE_KEY,
  STRIPE_WEBHOOK_KEY,
  STRIPE_PRICE_ID,
};
