const STRIPE_SECRET_KEY =
  "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";
const STRIPE_PUBLISHABLE_KEY =
  "pk_live_51QsQzNL7QJgb8vM73DD1rfi7SQOZZulzMgwfpRnNU0aZon4bjr5RvjOOHcUtoYpoVNWfUhZayZLkFIk5zMI6zNcY00TwNoC2zc";
const STRIPE_WEBHOOK_KEY = "whsec_9AeG0LIX9YcqMhh9UJjp73LdMViOgUXm";
const STRIPE_PRICE_ID_MONTHLY = "price_1QsRCaL7QJgb8vM7SN7jDRQw";
const STRIPE_PRICE_ID_YEARLY = "price_1QsRE1L7QJgb8vM7hbAPg577";
const STRIPE_PRICE_ID_LIFETIME = "price_1RbkkJL7QJgb8vM7HLC90Fml";

module.exports = {
  STRIPE_SECRET_KEY,
  STRIPE_PUBLISHABLE_KEY,
  STRIPE_WEBHOOK_KEY,
  STRIPE_PRICE_ID_MONTHLY,
  STRIPE_PRICE_ID_YEARLY,
  STRIPE_PRICE_ID_LIFETIME,
};
