const STRIPE_SECRET_KEY =
  "sk_test_51MPpHXARPqfde7N5Uo2L5r9E3MZwR7qNHPKbCFvIrqJa3pnzcm3tV6TRRksCP4ZEC7bugRFOkzjnJ4oXgESlARaN00nakZTXkG";
const STRIPE_PUBLISHABLE_KEY =
  "pk_test_51MPpHXARPqfde7N5ZVZicL8SRNwvzvoyFe7vCgCID73swbWAn0JtbjuscgsC0mQmbZrdW7w340LOLAVV0TadxV6e00LNsJGPyl";
const STRIPE_WEBHOOK_KEY = "whsec_9AeG0LIX9YcqMhh9UJjp73LdMViOgUXm";
const STRIPE_MONTHLY_MEMBERSHIP_PRICE_ID = "price_1PK3RpARPqfde7N5quECV3n1";
const PRICE = 1500;

module.exports = {
  STRIPE_SECRET_KEY,
  STRIPE_PUBLISHABLE_KEY,
  STRIPE_WEBHOOK_KEY,
  STRIPE_MONTHLY_MEMBERSHIP_PRICE_ID,
  PRICE,
};
