image: jangoro/jangoro-backend:latest

options:
  docker: true

pipelines:
  # default:
    # - parallel:
      # - step:
      #     name: Code linting
      #     script:
      #       - echo "Running lint..."
      #       - npm install eslint
      #       - npx eslint .
      # - step:  
      #     name: Build
      #     script:
      #       - echo "Running build..."
      #       - npm install
      #       - npm run build
      # - step:  
      #     name: Test
      #     script:
      #       - echo "Running tests..."
      #       - npm install
      #       - npm run test
  branches:
    dev:
      - step:
          name: Build, Tag and Push the Dev Docker image
          script:
            - echo "Logging in to Docker registry"
            - echo "huddl35mart!" | docker login --username jangoro --password-stdin
            - docker system prune -af
            - echo "Building Docker image"
            - docker build -t jangoro-backend:latest .
            - echo "Tagging Docker image"
            - docker tag jangoro-backend:latest jangoro/jangoro-backend
            - docker images
            - echo "Pushing Docker image to registry"
            - docker push jangoro/jangoro-backend
    stage:
      - step:
          name: Build, Tag and Push the Stage Docker image
          script:
            - echo "Logging in to Docker registry"
            - echo "huddl35mart!" | docker login --username jangoro --password-stdin
            - docker system prune -af
            - echo "Building Docker image"
            - docker build -t jangoro-backend:stage .
            - echo "Tagging Docker image"
            - docker tag jangoro-backend:stage jangoro/jangoro-backend:stage
            - docker images
            - echo "Pushing Docker image to registry"
            - docker push jangoro/jangoro-backend:stage